realm=chat.ebra.dev
listening-port=3479
tls-listening-port=5350
min-port=13000
max-port=15999
no-software-attribute
use-auth-secret
static-auth-secret-file=/var/turn_secret
cert=/etc/coturn/certs/wildcard_.ebra.dev.crt
pkey=/etc/coturn/certs/wildcard_.ebra.dev.key
log-file=stdout
